### ISSUE TITLE
Move functions from notebook to Python module file and use %run or %load.

### ISSUE THREAD

**Issue by piyanatk** [UKZN-Astronomy/hirax_corrcal#1]
Jupyter notebook has `%run` and `%load` magic commands that will, respectively, execute or append, codes in `.py` file to the notebook. I suggest the followings to improve your workflow:

- [ ] Move the functions that you might be using in multiple notebooks into a Python module (`.py` file)
- [ ] Use either `%run` and `%load` to make the functions available to the notebooks.

Doing these has two benefits:
1. You have all of your functions in one place so they are easier to maintain.
2. The magic commands let you use the functions in the notebook without having to use `PYTHON_PATH` environment variable or add a module to `system.path`.

This is the method that I recommend when most of your analysis are done in Jupyter notebooks and when your code base is still growing.

**Comment by Zahra-Kader** [comment]
Thanks, I have implemented this by pushing the functions to `Functions.py'

**Comment by piyanatk** [comment]
Great! I will close this issue.
