### ISSUE TITLE
Switch to UKZN-Astronomy/corrcal

### ISSUE THREAD

**Issue by piyanatk** [UKZN-Astronomy/hirax_corrcal#16]
Would it be hard to switch the `corrcal` version that you are using to the one in https://github.com/UKZN-Astronomy/corrcal? I think it is becoming clear that we will at least try `corrcal` on HIRAX, so I would like to get the development going, and the best way to proceed is probably to use and test it. I plan to keep the underlying calculation the same for now and just improve on  the documentation and user interface as necessary. For example, we could add a function to save `corrcal` gain solutions to `draco` readable format. This can wait until you have some parts of the pipeline running, and I can handle the switch.

**Comment by Zahra-Kader** [comment]
Yip, it's a good idea to continue with corrcal documentation. I am using the corrcal version in UKZN-Astronomy, and it was not hard to switch. I did this a few months back. 
I set up the code to save the corrcal gains and create an h5 file with a `gain` header to store them. Adding a function in corrcal that can take care of this would be pretty neat.

**Comment by piyanatk** [comment]
Great. Can you make issues in UKZN-Astronomy/corrcal repo for anything you think might be good to add, more documentation, renaming, functions to interact with `draco`, etc? Let's also leave this issue opened for now.

**Comment by piyanatk** [comment]
I think Zahra have tried this so we will close it.
