### ISSUE TITLE
Set up ReviewNB

### ISSUE THREAD

**Issue by piyanatk** [UKZN-Astronomy/hirax_corrcal#6]
[reviewnb.com](https://www.reviewnb.com/) is a GitHub web app that lets you see the visual differences, compare, and comment on committed changes to Jupyter notebook files. I have installed it on my GitHub account and _maybe_ on the UKZN-Astronomy organisation, but I am not sure ...

@Zahra-Kader Can you check by:
* Go to [reviewnb.com](https://www.reviewnb.com/) and login with your GitHub account
* You should see UKZN-Astronomy/hirax_corrcal repository.<img width="553" alt="Screenshot 2020-08-11 at 16 31 08" src="https://user-images.githubusercontent.com/2381361/89910309-5735d080-dbf0-11ea-9762-3908c7915472.png">
* Selecting it should give you a list of the files in the repository, where you will be able to select Jupyter notebook files.
<img width="410" alt="Screenshot 2020-08-11 at 16 31 32" src="https://user-images.githubusercontent.com/2381361/89910557-ada30f00-dbf0-11ea-9fcb-22aaf41efea7.png">
* Once you select a notebook file, going to CHANGES tab will show all previous committed changes.
<img width="925" alt="Screenshot 2020-08-11 at 16 31 47" src="https://user-images.githubusercontent.com/2381361/89910681-d4f9dc00-dbf0-11ea-8c1a-396ea65b11ec.png">
* Selecting on any of the changes will show the visual differences of the notebooks.
<img width="1437" alt="Screenshot 2020-08-11 at 16 32 10" src="https://user-images.githubusercontent.com/2381361/89910769-ee9b2380-dbf0-11ea-9559-610726633fcd.png">

**Comment by Zahra-Kader** [comment]
Yip, when I click on the link and go to the hirax_corrcal repository, I can navigate it as you have shown here

**Comment by piyanatk** [comment]
Great! I will close this issue than.
