### ISSUE TITLE
Convert lines that assign functions as variables into import statements

### ISSUE THREAD

**Issue by piyanatk** [UKZN-Astronomy/hirax_corrcal#8]
It is okay to assign a function as a variable, but you usually do so when you need to alter the behaviour of the function, e.g. fix certain input parameters. For an assignment with no change like below, using `namespace` in Python import statement is a better choice. So instead of ... 
https://github.com/UKZN-Astronomy/hirax_corrcal/blob/784e8f46523d0aeaabce9098a0b130b460b23ae5/Functions.py#L421
... you would do
```python
import numpy.random.normal as rand_normal
```

**Comment by Zahra-Kader** [comment]
Thanks! I fixed that

**Comment by piyanatk** [comment]
@Zahra-Kader Great. You can close this issue.
