### ISSUE TITLE
Line numbers still not showing up in jupyter notebooks on Github, though they are present in the notebooks on my laptop

### ISSUE THREAD

**Issue by Zahra-Kader** [UKZN-Astronomy/hirax_corrcal#9]
This is probably a simple fix - I'm going to try fixing this so that I can reference line numbers in the Issues

**Comment by piyanatk** [comment]
The line numbers show up okay in ReviewNB, so don't worry too much about this if it doesn't work.

**Comment by Zahra-Kader** [comment]
I'm going to close this issue because it isn't too important.
